// Generate the capture bridge module: embeds selected elites' genome JSONs
// so the ?bgshot capture harness can render them WITHOUT registry entries.
// Genomes stay genome JSONs; registration is session-only via the imported-
// robot registry (custom: ids), worktree-only.
//
// Usage: node gen-capture.mjs --archive /tmp/p1c/archive.json --ids bt-p1-0210,bt-p1-2201 \
//     --out /private/tmp/p1c-wt/src/robots/bt/mapelites-capture.ts

import { readFileSync, writeFileSync } from 'node:fs';

function arg(name: string, def: string): string {
    const i = process.argv.indexOf(`--${name}`);
    return i >= 0 && i + 1 < process.argv.length ? (process.argv[i + 1] as string) : def;
}

const archivePath = arg('archive', '/tmp/p1c-archive.json');
const out = arg('out', '/tmp/p1c-wt/src/robots/bt/mapelites-capture.ts');
const ids = arg('ids', '')
    .split(',')
    .map((s) => s.trim())
    .filter((s) => s.length > 0);

const archive = JSON.parse(readFileSync(archivePath, 'utf8')) as {
    cells: Array<{
        id: string;
        genome: string;
        nodes: number;
        fit: { score: number; wins: number };
        profile: { aggression: number; padsPerMatch: number; meanDist: number; driveActivity: number };
    }>;
};

const cells = ids.length > 0 ? archive.cells.filter((c) => ids.includes(c.id)) : archive.cells;
const missing = ids.filter((id) => !archive.cells.some((c) => c.id === id));
if (missing.length > 0) {
    console.error(`[gen-capture] missing ids: ${missing.join(', ')}`);
    process.exit(1);
}

const entries = cells
    .map((c) => {
        const p = c.profile;
        const blurb = `cell [${c.id.replace('bt-p1-', '')}] wins=${c.fit.wins} agg=${p.aggression.toFixed(2)} pads=${p.padsPerMatch.toFixed(1)}/m dist=${p.meanDist.toFixed(0)}u`;
        return `    {\n        id: '${c.id}',\n        name: '${c.id}',\n        blurb: ${JSON.stringify(blurb)},\n        nodes: ${c.nodes},\n        genome: ${JSON.stringify(c.genome)},\n    },`;
    })
    .join('\n');

const src = `// GENERATED by tools/map-elites/gen-capture.ts — do not hand-edit.
// Capture bridge: embeds MAP-Elites genome JSONs for the ?bgshot harness.
// These are NOT registry entries: the harness registers them session-only
// via the imported-robot registry (custom: ids) from these genome strings.
export interface CaptureGenome {
    id: string;
    name: string;
    blurb: string;
    nodes: number;
    /** Schema-versioned genome JSON (see src/robots/bt/serialization.ts). */
    genome: string;
}

export const P1_CAPTURE_GENOMES: CaptureGenome[] = [
${entries}
];
`;
writeFileSync(out, src);
console.log(`[gen-capture] wrote ${cells.length} capture genomes -> ${out}`);
