// Chassis V3: all face EAST (+x), native 32x32 (engine bakes w:32 h:32,
// 46px direction frames via dir8SizeFor; see src/game/art.ts).
// Hand-drawn at native resolution from the robot-chassis concept sheet
// (red tank / blue hex / green spiky / yellow industrial / purple spider /
// cyan missiles / orange hammer / pink sleek): silhouettes carry the design
// identity; hulls stay neutral so the bake works unchanged.
// Team identity is trim/lens-only: `t` (team trim, baked per-team by the
// engine track) marks visor/cockpit lenses plus one trim stripe per
// hull (turret/ghost carry the lens band only, as in V3 16x16). Hull
// bodies stay `w` (neutral steel). No large `t` areas.
// Shading chars: k d m l w + s/h cool-shadow support; `c` warm specular.

export const CHASSIS_V2: Record<string, string[]> = {
    // V3 rusher (orange hammer) at 32px: wedge body + full-height hammer-head nose plate with team-inlay face band, haft handle, west trim stripe.
    rusher: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '........................kkkkkkkk',
        '....kkkkkkkkkkkkkkkkkkkkkwwwwwwk',
        '..kllllllllllllllllllllkkwwwwwwk',
        '..kllllllllllllllllllllkkddddddk',
        '..ktwwwwwwwwwwwwwwwwwwwkkdwmwwmk',
        '..ktwwwwwwwwwwmwwwwwwwwkkdwwwwwk',
        '..ktwwwwwwwwwwmwwwwwwwwkkdcwttwk',
        '..ktwwwwwwwwwwwwwwwwwwwkkdwwttwk',
        '..ktwwwwwwwwwwwwwwwwddddkdwwttwk',
        '..ktwwwwwwwwwwwwwwwwmmmmkdwwttwk',
        '..ktwwwwwwwwwwwwwwwwmmmmkdwwttwk',
        '..ktwwwwwwwwwwwwwwwwddddkdwwttwk',
        '..ktwwwwwwwwwwwwwwwwwwwkkdwwttwk',
        '..ktwwwwwwwwwwwwwwwwwwwkkdwwttwk',
        '..ktwwwwwwwwwwwwwwwwwwwkkdwmwwmk',
        '..ktdddddddddddddddddddkkdwwwwwk',
        '..kdddddddddddddddssssskkddddddk',
        '..kdddddddddddddddssssskkwwwwwwk',
        '....kkkkkkkkkkkkkkkkkkkkkwwwwwwk',
        '........................kkkkkkkk',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................'
    ],
    // V3 turret (green spiky) at 32px: bunker slab, five tall spikes top and bottom, visor band with core, triple nose prongs.
    turret: [
        '................................',
        '................................',
        '...............kk...............',
        '..........k...kkkk...k..........',
        '.....k...kkk..kwwk..kkk...k.....',
        '....kkk..kwk..kwwk..kwk..kkk....',
        '....kwk..kwk..kwwk..kwk..kwk....',
        '....kwk..kwk..kwwk..kwk..kwk....',
        '....kwk..kwk..kwwk..kwk..kwk....',
        '..kkkkkkkkkkkkkkkkkkkkkkkkkkk...',
        '..kkkkkkkkkkkkkkkkkkkkkkkkkkk...',
        '..klllllllllllllllllllllllllk...',
        '..kwwwwwwwwwwwwwwwwwwwwwwwwwkwwk',
        '..kwwwwwwwwwwwwwwwwwwwwwwwwwkwwk',
        '..kwwwwwwwwwwwwwwwwwwwwwwwwwk...',
        '..kwwwwhttttttccttttttthwwwwkwwk',
        '..kwwwwwtttttttttttttttwwwwwkwwk',
        '..kwwwwwwwwwwwwwwwwwwwwwwwwwk...',
        '..kwwwwwwwwwwwwwwwwwwwwwwwwwkwwk',
        '..kwwwwwwwwwwwwwwwwwwwwwwwwwkwwk',
        '..kddddddddddddddmssssssssssk...',
        '..kkkkkkkkkkkkkkkkkkkkkkkkkkk...',
        '..kkkkkkkkkkkkkkkkkkkkkkkkkkk...',
        '....kwk..kwk..kwwk..kwk..kwk....',
        '....kwk..kwk..kwwk..kwk..kwk....',
        '....kwk..kwk..kwwk..kwk..kwk....',
        '....kkk..kwk..kwwk..kwk..kkk....',
        '.....k...kkk..kwwk..kkk...k.....',
        '..........k...kkkk...k..........',
        '...............kk...............',
        '................................',
        '................................'
    ],
    // V3 orbiter (purple spider) at 32px: diamond hull with abdomen, six jointed two-segment legs (knee blocks, ring joints), eye cluster, dorsal stripe, fangs + mouth nose.
    orbiter: [
        '................................',
        '..kk...........k..........kk.dk.',
        '...mk.........kdk........k.dm.k.',
        '....kdkk......kdk.......kkd.kk..',
        '......kk......kdk......kkk.k....',
        '.......k......kdk.....k.d.......',
        '........k.....kmk....k.d.k......',
        '.........k....kdk...k.m.k.......',
        '..........k..kkkkkkk.d.k........',
        '...........kllllllmlk.k.........',
        '..........klllclllmlllk.........',
        '.........klclllwwwmwwwwk........',
        '.........klllllwwwmwwwwwkkkwwww.',
        '.....kwwwkwwwwwwwwwwttttkkkkkkw.',
        '...klllllwwwwwwwwwmwwwwwkkkkkkkk',
        '...kwwwwwwttttttttwwwwwwkddddddk',
        '...kwwwwwwttttttttwwwwwwkddddddk',
        '...klllllwwwwwwwwwmwwwwwkkkkkkkk',
        '.....kwwwkwwwwwwwwwwttttkkkkkkw.',
        '.........klllllwwwmwwwwwkkkwwww.',
        '.........kddddddddmddddk........',
        '..........kdddddddmhhhk.........',
        '...........kdddddhhhk.k.........',
        '..........k..kkkkkkk.d.k........',
        '.........k....kdk...k.m.k.......',
        '........k.....kmk....k.d.k......',
        '.......k......kdk.....k.d.......',
        '......kk......kdk......kkk.k....',
        '....kdkk......kdk.......kkd.kk..',
        '...mk.........kdk........k.dm.k.',
        '..kk...........k..........kk.dk.',
        '................................'
    ],
    // V3 wanderer (yellow industrial) at 32px: riveted shell, exhaust stacks, cab goggles, side stripe, radiator-grille plow reaching the east edge (V3 stopped short).
    wanderer: [
        '................................',
        '................................',
        '.....kkk..kkk...................',
        '.....kdk..kdk...................',
        '.....kdk..kdk...................',
        '.....kkkkkkkk...................',
        '..kkkkkkkkkkkkkkkkkkkkkkkkkk....',
        '..klmlmlmlmlmlmlmlmlmlmlmlmk....',
        '..kwwwwwwwwwwwwwwwkllllllkwk....',
        '..kllllllwwwwwwwwwkddddddkwk....',
        '..kwwwwwwwwwwwwwwwkttkttdkwk....',
        '..kwwwwwwwwwwwwwwwkctkttdkwk....',
        '..kwwwwwwwwwwwwwwwdddddddkkkkkk.',
        '..kwwwwwwwwwmwwwwwdddddddkcdwdk.',
        '..kwwwwwwwwwmwwwwwwwwwwwwkwdwdkk',
        '..kwwwwwwwwwmttttttttwwwwkwdwdkk',
        '..kwwwwwwwwwmttttttttwwwwkwdwdkk',
        '..kwwwwwwwwwmwwwwwwwwwwwwkwdwdkk',
        '..kdddddddddmwwwwwwwwwwwwkwdwdk.',
        '..kdddddddddmwwwwwssssssskkkkkk.',
        '..ksssssssssssssshhhhhhhhkwk....',
        '..kddddddddddddddddddddddkkk....',
        '..klmlmlmlmlmlmlmlmlmlmlmlmk....',
        '..kkkkkkkkkkkkkkkkkkkkkkkkkk....',
        '....kkkk......kkkk....kkkk......',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................'
    ],
    // V3 sniper (cyan missiles) at 32px: scope hump with ocular lens, long hull with panel seam, 3-tube rack with rimmed tube mouths (wide-bore main gun).
    sniper: [
        '................................',
        '................................',
        '................................',
        '................................',
        '......kkkkkkkk..................',
        '......kllllllk..................',
        '......kllllttk..................',
        '......kddddddk..................',
        '......kkkkkkkk..................',
        '..kkkkkkkkkkkkkkkkkkkkkkkkk.....',
        '..kttttttttttlllllllllllllk.....',
        '..kwcwwwwwwwmwwwwwwwkkkkkkkkkkk.',
        '..kwwwwwwwwwmwwwwwwwwwwwwwwdddkd',
        '..kwwwwwwwwwmwwwwwwwkkkkkkkkkkk.',
        '..kwwwwwwwwwmwwwwwwwkkkkkkkkkk..',
        '..kwwwwwwwwwmwwwwwwwwwwwwddddkdd',
        '..kwwwwwwwwwmwwwwwwwwwwwwddddkdd',
        '..kwwwwwwwwwmwwwwwwwkkkkkkkkkk..',
        '..kwwwwwwwwddddddhhhkkkkkkkkkkk.',
        '..kwwwwwwwwdddddddddwwwwwwwdddkd',
        '..kwwwwwwwwdddddddddkkkkkkkkkkk.',
        '..kddddddddddddsssssssssssk.....',
        '..kkkkkkkkkkkkkkkkkkkkkkkkk.....',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................'
    ],
    // V3 brawler (red tank) at 32px: tread bands with road-wheel hubs, turret dome with round team lens on a d bed, cannon barrel with muzzle brake + bore nose.
    brawler: [
        '................................',
        '................................',
        '................................',
        '....kkkkkkkkkkkkkkkkkkkk........',
        '..kkddddddddddddddddddkk........',
        '..kkdmkddddmkddddmkdddkk........',
        '..kkddddddddddddddddsskk........',
        '....kkkkkkkkkkkkkkkkkkkk........',
        '..kkkkkkkkkkkkkkkkkkkkkkkkkk....',
        '..kwwwwllllllllllllwwwwwwwwk....',
        '..kwwwkkkkkkkkkkkkkkwwwwwwwk....',
        '..kwwwkllllllllllllkwwwwwwwk....',
        'ktwwwwkllwwwwwwwwwwkwwwwllllllk.',
        'ktwwwwkwwddddddddwwkwwwwwwwwwwk.',
        'ktwwwwkwwddddddddwwkkkkkkkkkkkk.',
        'ktwwwwkwwddttttddwwkwwwwwwwwddkd',
        'ktwwwwkwwddtcctddwwkwwwwwwwwddkd',
        'ktwwwwkwwddddddddwwkkkkkkkkkkkk.',
        'ktwwwwkwwddddddddwwkwwwwssssssk.',
        'ktwwwwkwwwwwwwwwwwwkwwwwwwwwwwk.',
        '..kwwwkddddddddddddksssssssk....',
        '..kwwwkkkkkkkkkkkkkksssssssk....',
        '..kwwwwwwddddddddddssssssssk....',
        '..kkkkkkkkkkkkkkkkkkkkkkkkkk....',
        '....kkkkkkkkkkkkkkkkkkkk........',
        '..kkddddddddddddddddsskk........',
        '..kkdmkddddmkddddmkdddkk........',
        '..kkddddddddddddddddddkk........',
        '....kkkkkkkkkkkkkkkkkkkk........',
        '................................',
        '................................',
        '................................'
    ],
    // V3 ghost (pink sleek) at 32px: slim arrowhead dart, swept fin blades, dorsal/ventral tailfins, canopy slit lens, exhaust notch, single-point nose.
    ghost: [
        '................................',
        '................................',
        '................................',
        '.......k........................',
        '........k.......................',
        '.........kk.....................',
        '..........wk....................',
        '...........kkk..................',
        '.............wk.................',
        '..............kkk...............',
        '................wk..............',
        '.................kk.............',
        '........wwwwwww....w............',
        '......kkkkkkkkkkkkkkkkkkkkkk....',
        '........kllllllllllllllllllllk..',
        '..ddwwwwwwwwwwcttttttwwwwwwwwwkw',
        '..ddwwwwwwwwwwtttttttwwwwwwwwwkw',
        '........kddddddddddddddddsshhk..',
        '......kkkkkkkkkkkkkkkkkkkkkk....',
        '........wwwwwww....w............',
        '.................kk.............',
        '................wk..............',
        '..............kkk...............',
        '.............wk.................',
        '...........kkk..................',
        '..........wk....................',
        '.........kk.....................',
        '........k.......................',
        '.......k........................',
        '................................',
        '................................',
        '................................'
    ],
    // V3 hunter (blue hex) at 32px: hex plating with facet seams, dorsal sensor mast, tail stripe + nose band with core, prow nose.
    hunter: [
        '................................',
        '................................',
        '..............kk................',
        '.............kwwk...............',
        '.............kclk...............',
        '.............kwwk...............',
        '.............kddk...............',
        '.............kkkkkk.............',
        '..........kkkkkkkkkkkk..........',
        '........kllllllllllllllk........',
        '......kllllllllmlllllllllk......',
        '.....klllllllmwwwwwwwwwwwwk.....',
        '....klllllwwwwwmwwwwwwwwwwwk....',
        '...kllllwwwwwwwmwwwwwwwwwwttk...',
        '..kwwwwwwwwwwwwmwwwwwwwwwwttwk..',
        '..kttttttwwwwwwmwwwwwwwwwwtcwwkw',
        '..kttttttwwwwwwmwwwwwwwwwwttwwkw',
        '..kwwwwwwwwwwwwmwwwwwwwwwwttwk..',
        '...kwwwwwwwddddmssssssssssssk...',
        '....kwwwwwwwdddmsssssssssssk....',
        '.....kwwwwwwwmssssssssssssk.....',
        '......kwwwwddddmhhhhhhhhhk......',
        '........kdddddddsssssssk........',
        '..........kkkkkkkkkkkk..........',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................'
    ],
};
