// Chassis V2 drafts: all face EAST (+x), 16x16.
// Palette chars: . k d m l w r g y, plus c (sniper scope glass) and
// b (ghost lens). No additions needed — existing palette only.

export const CHASSIS_V2: Record<string, string[]> = {
    // Aggressive wedge: narrow rear, armored nose pointing east, red lens.
    rusher: [
        '................',
        '...kkkk.........',
        '.kkwwwwkk.......',
        '.kwlllwwwkk.....',
        '.kwllldwwwkkk...',
        '.kwllddwwwwwkk..',
        'kkwlwddwwwwwwwk.',
        'kwmlwddrwwwwwwwk',
        'kwmlwddrwwwwwwwk',
        'kkwlwddwwwwwwwk.',
        '.kwllddwwwwwkk..',
        '.kwllldwwwkkk...',
        '.kwlllwwwkk.....',
        '.kkwwwwkk.......',
        '...kkkk.........',
        '................',
    ],
    // Wide bunker: tall armored slab, flat east face, amber viewport band.
    turret: [
        '................',
        '.kkkkkkkkkkkkk..',
        '.klllllllllllk..',
        'kdkwwwwwwwwwwdk.',
        'kdkwmmmmmmmmwdkk',
        'kdkwmdddddmmwddk',
        'kdkwmdddddmmwddk',
        'kddwmyyyyyymwddk',
        'kddwmyyyyyymwddk',
        'kdkwmdddddmmwddk',
        'kdkwmdddddmmwddk',
        'kdkwmmmmmmmmwdkk',
        'kdkwwwwwwwwwwdk.',
        '.klllllllllllk..',
        '.kkkkkkkkkkkkk..',
        '................',
    ],
    // Sleek dart: thin needle fuselage, green lens stripe at the nose.
    orbiter: [
        '................',
        '................',
        '................',
        '.kk.............',
        '.kwwkk..........',
        '.kwlwkkk........',
        '.kwllwwkkkk.....',
        '.kwllwwwwwwwkkk.',
        'kwmlddwwwwwwwwgk',
        'kwmlddwwwwwwwwgk',
        '.kwllwwwwwwwkkk.',
        '.kwllwwkkkk.....',
        '.kwlwkkk........',
        '.kwwkk..........',
        '.kk.............',
        '................',
    ],
    // Round bug: circular shell, leg nubs, green goggle eyes facing east.
    wanderer: [
        '................',
        '..k..kkkk..k....',
        '..k.kwwwwk.k....',
        '...kwwlllwk.....',
        '..kwwllddllk....',
        '.kwwllddddllk...',
        '.kwllddwwddlk...',
        'kkwlddwggwddwkk.',
        'kkwlddwggwddwkk.',
        '.kwllddwwddlk...',
        '.kwwllddddllk...',
        '..kwwllddllk....',
        '...kwwlllwk.....',
        '..k.kwwwwk.k....',
        '..k..kkkk..k....',
        '................',
    ],
    // Long rifle: narrow marksman body, barrel nose to the east edge, amber scope.
    sniper: [
        '................',
        '...kkkkkkk......',
        '.kkwwwwwwwkk....',
        '.kwlllllwwddk...',
        '.kwldddlwwdddk..',
        '.kwldddlllwdddk.',
        'kkwlddddldwddddk',
        'kwmldkddcckdddkk',
        'kwmldkddcckdddkk',
        'kkwlddddldwddddk',
        '.kwldddlllwdddk.',
        '.kwldddlwwdddk..',
        '.kwlllllwwddk...',
        '.kkwwwwwwwkk....',
        '...kkkkkkk......',
        '................',
    ],
    // Bruiser slab: wide armored hull, heavy plate bands, red visor lens.
    brawler: [
        '................',
        '..kkkkkkkkkk....',
        '.kwwwwwwwwwwk...',
        '.kwlllllllwwk...',
        'kkwlllllddwwwkk.',
        'kwmlllddddwwwwdk',
        'kwmlldddddwwwwdk',
        'kwmddddddrrwwwwk',
        'kwmddddddrrwwwwk',
        'kwmlldddddwwwwdk',
        'kwmlllddddwwwwdk',
        'kkwlllllddwwwkk.',
        '.kwlllllllwwk...',
        '.kwwwwwwwwwwk...',
        '..kkkkkkkkkk....',
        '................',
    ],
    // Stealth wedge: pale-edged arrowhead narrowing east, blue ghost lens.
    ghost: [
        '................',
        '......kkkk......',
        '....kkwwwwkk....',
        '...kwwlllwwk....',
        '..kwwllddllwk...',
        '..kwllddddllwk..',
        '.kwwllddddllwwk.',
        '.kwllddkbbkddlwk',
        '.kwllddkbbkddlwk',
        '.kwwllddddllwwk.',
        '..kwllddddllwk..',
        '..kwwllddllwk...',
        '...kwwlllwwk....',
        '....kkwwwwkk....',
        '......kkkk......',
        '................',
    ],
    // Scope predator: angular hunter with red 2x2 scope sight amid dark panels.
    hunter: [
        '................',
        '...kkkkkkkk.....',
        '.kkwwwwwwwkk....',
        '.kwlllllwwddk...',
        '.kwldddlwwdddk..',
        '.kwldddllwddddk.',
        'kkwlddddldwddddk',
        'kwmldkddrrkddddk',
        'kwmldkddrrkddddk',
        'kkwlddddldwddddk',
        '.kwldddllwddddk.',
        '.kwldddlwwdddk..',
        '.kwlllllwwddk...',
        '.kkwwwwwwwkk....',
        '...kkkkkkkk.....',
        '................',
    ],
};
