// Obstacle face-plates from the LOCKED obstacle sheet, top row (native
// 32x32 medallions — exact 2x integer upscale of the locked 16x16 maps,
// designs preserved pixel-for-pixel, <=6 colors each). Rendered 1:1 over the
// tiled barrier base in BattleScene; variant picked deterministically.

type PixelMap = string[];

// CRATE_A: hazard-striped plate.
// Opaque colors: hklmsw.
export const CRATE_A: PixelMap = [
    '..wwwwwwmmwwwwwwwwwwllsswwwwww..',
    '..wwwwwwmmwwwwwwwwwwllsswwwwww..',
    '..wwwwllmmwwwwwwwwwwwwmmllwwww..',
    '..wwwwllmmwwwwwwwwwwwwmmllwwww..',
    'ssllllkkllhhkkllhhhhllkkllhhhhww',
    'ssllllkkllhhkkllhhhhllkkllhhhhww',
    'llhhkkhhhhkkllllkkllkksshhkksshh',
    'llhhkkhhhhkkllllkkllkksshhkksshh',
    'llhhmmkkhhhhhhsssskksshhkkmmhhll',
    'llhhmmkkhhhhhhsssskksshhkkmmhhll',
    '..mmhhhhkkkksssskkmmsskkhhhhhh..',
    '..mmhhhhkkkksssskkmmsskkhhhhhh..',
    '..ssllmmssmmmmmmwwllmmssmmllmm..',
    '..ssllmmssmmmmmmwwllmmssmmllmm..',
    '..llllhhmmmmmmllllmmmmmmhhllll..',
    '..llllhhmmmmmmllllmmmmmmhhllll..',
    '..llllhhmmmmmmmmmmmmmmmmhhllll..',
    '..llllhhmmmmmmmmmmmmmmmmhhllll..',
    '..llllssmmmmmmmmmmmmmmmmssllll..',
    '..llllssmmmmmmmmmmmmmmmmssllll..',
    '..llmmssssmmmmmmmmmmmmsssssshh..',
    '..llmmssssmmmmmmmmmmmmsssssshh..',
    '..llmmhhkkssssssmmhhhhkkhhllll..',
    '..llmmhhkkssssssmmhhhhkkhhllll..',
    '..mmmmhhllllllllllllllllmmhhmm..',
    '..mmmmhhllllllllllllllllmmhhmm..',
    'wwllllmmmmmmmmmmmmmmmmmmmmllllww',
    'wwllllmmmmmmmmmmmmmmmmmmmmllllww',
    'mmhhmmllmmssmmmmmmmmhhllllmmhhhh',
    'mmhhmmllmmssmmmmmmmmhhllllmmhhhh',
    'kkkkkkhhkkkksssssssskkhhkkhhkkkk',
    'kkkkkkhhkkkksssssssskkhhkkhhkkkk',
];

// CRATE_B: teal X-brace plate.
// Opaque colors: bdgkmw.
export const CRATE_B: PixelMap = [
    'wwwwwwmmmmggmmmmggmmmmmmggwwwwww',
    'wwwwwwmmmmggmmmmggmmmmmmggwwwwww',
    'wwggggddkkkkkkkkkkkkkkkkddgggggg',
    'wwggggddkkkkkkkkkkkkkkkkddgggggg',
    'wwmmddkkbbggggggggggggbbddddmmgg',
    'wwmmddkkbbggggggggggggbbddddmmgg',
    'kkkkkkddggggwwwwwwwwwwbbddkkkkkk',
    'kkkkkkddggggwwwwwwwwwwbbddkkkkkk',
    'mmddbbkkddggwwwwwwggbbddddbbddmm',
    'mmddbbkkddggwwwwwwggbbddddbbddmm',
    'mmddggggddddbbwwwwbbddkkggbbmmmm',
    'mmddggggddddbbwwwwbbddkkggbbmmmm',
    'mmmmggwwwwddddbbbbddddggwwggmmmm',
    'mmmmggwwwwddddbbbbddddggwwggmmmm',
    'mmmmggwwwwwwddddddkkggwwwwggmmmm',
    'mmmmggwwwwwwddddddkkggwwwwggmmmm',
    'mmmmggwwwwwwbbddddmmwwwwwwggmmmm',
    'mmmmggwwwwwwbbddddmmwwwwwwggmmmm',
    'mmddggwwwwbbddddkkddbbwwwwggmmdd',
    'mmddggwwwwbbddddkkddbbwwwwggmmdd',
    'mmmmggwwbbddddggwwddddmmwwggddmm',
    'mmmmggwwbbddddggwwddddmmwwggddmm',
    'mmmmbbbbddkkggwwwwwwddddmmbbddkk',
    'mmmmbbbbddkkggwwwwwwddddmmbbddkk',
    'mmmmmmddddbbwwwwwwwwggddddmmmmgg',
    'mmmmmmddddbbwwwwwwwwggddddmmmmgg',
    'wwggggddbbbbggggwwggggbbddwwggww',
    'wwggggddbbbbggggwwggggbbddwwggww',
    'wwggggddmmmmmmmmmmmmmmmmmmgggggg',
    'wwggggddmmmmmmmmmmmmmmmmmmgggggg',
    'ddkkddddkkkkkkkkkkkkkkkkkkmmkkdd',
    'ddkkddddkkkkkkkkkkkkkkkkkkmmkkdd',
];

// CRATE_C: rust hazard-band plate.
// Opaque colors: chklmw.
export const CRATE_C: PixelMap = [
    '..............wwll..............',
    '..............wwll..............',
    '................................',
    '................................',
    '..wwwwwwwwhhllwwhhccwwhhwwwwww..',
    '..wwwwwwwwhhllwwhhccwwhhwwwwww..',
    '..wwwwwwkkkkwwkkllwwkkllllwwll..',
    '..wwwwwwkkkkwwkkllwwkkllllwwll..',
    '..wwmmmmhhwwkkhhcckkllccmmmmll..',
    '..wwmmmmhhwwkkhhcckkllccmmmmll..',
    '..hhhhkkhhhhkkhhhhkkkkkkkkhhhh..',
    '..hhhhkkhhhhkkhhhhkkkkkkkkhhhh..',
    '..wwllhhmmmmllllllllllmmllllmm..',
    '..wwllhhmmmmllllllllllmmllllmm..',
    '..llwwkkllllllllllllllllllllll..',
    '..llwwkkllllllllllllllllllllll..',
    '..wwllmmllllllllllllllllllllww..',
    '..wwllmmllllllllllllllllllllww..',
    '..wwmmhhllllllllllllllllllhhll..',
    '..wwmmhhllllllllllllllllllhhll..',
    '..hhhhmmllllllllllllllmmllllll..',
    '..hhhhmmllllllllllllllmmllllll..',
    '..llllmmllllmmllllllllllllllmm..',
    '..llllmmllllmmllllllllllllllmm..',
    '..wwwwllhhhhhhmmmmhhmmhhwwwwww..',
    '..wwwwllhhhhhhmmmmhhmmhhwwwwww..',
    '..wwllllkkllcckkwwcckkccwwllww..',
    '..wwllllkkllcckkwwcckkccwwllww..',
    '..llmmllllcckkcccckkccllllllll..',
    '..llmmllllcckkcccckkccllllllll..',
    '..mmhhmmcckkhhcckkllllkkhhhhhh..',
    '..mmhhmmcckkhhcckkllllkkhhhhhh..',
];
