// Powerup pads from the LOCKED powerup-pad sheet (native 32x32,
// box-sampled, game-palette quantized, <=10 colors each). Kind glyph + ring
// baked in; the PAD_RADIUS pickup pulse stays a vector overlay (radius info).

type PixelMap = string[];

// PAD_WARD: blue shield ring — kind-neutral "charging" marker for dark pads.
// Opaque colors: bdklpqsw.
export const PAD_WARD: PixelMap = [
    '...........kkkkkkpkkk...........',
    '.........kpddbbbbbbddpk.........',
    '.....bbkkbbbssbbbbbsbbbkdb......',
    '...b.bkblbbbbbwwwwbbbbbbbb......',
    '..bwbpbbbbwwwbwwwwbwwwbdbbd.....',
    '..bbbbbblbwwwbblllbwwwblbbbd....',
    '...kblbwwbblbssssssblbbwwbbbdb..',
    '...dbwwwwldsbbllllbbsdwwwwwbd...',
    '..kbbwwwlbbbllllllllbbbwwwlsbk..',
    '.ksbbbbwbblllbbbbbblllbbwbbbbsk.',
    '.pbbwwbbbllllbwwwwdllllbsbwwbbp.',
    'ksbbwwlblbbbbwlbblwbbbblblwwwbsk',
    'kssbwwbblbwllbwwwwbbbbblbbwwbddk',
    'kbsbbbbblbwbwwwwwwwlbbblbsbbbsbk',
    'kbbwwbbllbwbwwwwwwwwbbbllbbwwbbk',
    'kbbwwbbllbwbwwwwwwwwbbbllbbwwbbk',
    'kbbwwbbllbwbwwwwwwwwbbbllbbwwbbk',
    'kbbwwbbllbbwwwwwwwwbwbbllbbwwbbk',
    'kbdbbbsbllbwwwwwwwwblbllbsbbbbbk',
    'kssbwwbbllbbwbwwwwbwbbllbbwwbsdk',
    'kbbwwwlslllbbwbwbbwbblwlblwwbbsk',
    '.dlwwwbsblllbbwlllbbllwbsbwwbbk.',
    '.kblbbblbbwllbbbbbbllwbslbbbbsk.',
    '..kbbwwwlbbllllbblllbbblwwlsbk..',
    '..dqbbwwwldbbbllllbbsqlwwwbbsk..',
    '...kbbbwwbblbsddddsblbbwwbwbp...',
    '....qbbblbwwwbbbbbbwwwblbbbsb...',
    '.....pbbpbwwwbwwwwbwwlbdbbkbb...',
    '......ksbbbbbbwwwwbbbbbbbk......',
    '.......kkbbbdsbbbbbsbbbkk.......',
    '.........kdddbbbbbbpdkk.........',
    '...........kkkkkkkkkk...........',
];

// PAD_AMP: gold bolt ring — amp (2x damage).
// Opaque colors: acklopqwy.
export const PAD_AMP: PixelMap = [
    '...........kkkpkkpkkk...........',
    '.........kpaayyyyyyaaqk.........',
    '.....yakkayoaaaaaaaayyakk.......',
    '...a.akayyayyywwwwyyyayaak......',
    '..ocypayaacwcywwwwycwcoayoa.....',
    '..ocoyyycycwcyyyyyawwcycyyok....',
    '...kayywwyycyaaaaaayccywcoyok...',
    '...qyccwwyqoyyyyyyyoaqywwwyya...',
    '..koacwwyaayyyyyyyyayaaywwcaok..',
    '.kayoyccyyyywwyyyycayyoayyyyyak.',
    '.pyaccyayyyycwyyycyyyyyoayccyyp.',
    'kayycwcaycyyyyyyywaycyyyacwwcyak',
    'kaaywcyoyyyyyyyywcayyyyyaocwyaak',
    'koayyoayyyyyyyywwoyyyyyyyayyyayk',
    'kyawwyayyyyyyywwwclcyyyyyaywwayp',
    'kyawwyayyyyyycwccccyayyyyaywwayp',
    'kyawwyayyyyywcccccyayyyyyaywwayp',
    'kyawwyayyyyaaaywcyayyyyyyaywwayp',
    'kyayyyayyyyyyycwyoyyycyyyayoyayp',
    'kaayccyayyycyycyaoyyywyyooccyaak',
    'kaywwwcayyyyycyayyyywwwcayccyoak',
    '.aywwcyayyyyacayyyyyywcoayccayk.',
    '.kacyyyyayyyaoyyyyyyycyayyyyoak.',
    '..kyacwwyaayayyyyyyyyoaywwcayk..',
    '...qoywwwyqaayyyyyyaaqywwcyyak..',
    '...kyoywwyycyaaaaaaycyywcoyyk...',
    '....qyoyyycccyyyyyycccycyyyq....',
    '.....qoyaacccycwwwycccaayyk.....',
    '......kaaoayyywwwwyyyayaak......',
    '.......kkayoaaaaaaaaoyakk.......',
    '.........kaaaooooooaaqk.........',
    '..........kkkpppppkkk...........',
];

// PAD_REPAIR: green cross ring — repair (+HP).
// Opaque colors: bdghklpqsw.
export const PAD_REPAIR: PixelMap = [
    '...........kkkkkkkkkk...........',
    '.........kkpksbbbbhkpkk.........',
    '.....gskkdsdqdssssdqdsdkdg......',
    '...h.skdgsdgggwwwwgggdsddd......',
    '..gwgkdsddggggwwwwhgggspsdk.....',
    '..ggshdgghggghgggghggghgghsp....',
    '...khggwwggghqpppqpggggwwggskh..',
    '...pggwwwgkqssbbbbsdqkgwwwggk...',
    '..kddwwwgddhgbbbbbbbhddgwwgqdk..',
    '.kqshggghgbbbbhhhhbbbbddgggggqk.',
    '.ksdgggdhgbbbsggggsbbbbddgggghk.',
    'kqsggggdbgbbbdwwwgdbbbbbdggggbqk',
    'kqqgggssbbbbbdwwwgdbbbbbddgggqpk',
    'ksdghsqhbbdddpwgggpdddbbhqhhgdsk',
    'khhwwgdbbslwwwwgggwwwgdbbdhwwhhk',
    'kbhwwgdbbdwwwgggggggggdbbdhwwhhk',
    'kbhwwgdbbdgwggggggggggdbbdgwwhhk',
    'khhwwgdbbdggggggggggghdbbdhwwhhk',
    'ksdghhqhbbdqqpwgggpdqdhbhqhhhdsk',
    'kdqgggsdbbbbbdwgggdbbbbbddgggqpk',
    'kdgwgggqbbbbbdwgggdbbbgbdggggsqk',
    '.dgwwggqsbbbbdhhhsdbbbgdqgggdsk.',
    '.kqgghggdsggbbddddbbbgsqggghdqk.',
    '..khdwwwgdggbbbbbbbbhgdgwwgdgk..',
    '..dksgwwwgkddhbbbbhdqkgwwwgsd...',
    '...ksdgwwggggqppppqggggwwgghk...',
    '....phsgghgggggggghggghgghhds...',
    '.....ksdkdggghwwwwhgggsphgkhh...',
    '......kddddgggwwwwgghdsddk......',
    '........kdhdpdddssdqdsdkk.......',
    '.........kkpkddddddkpkk.........',
    '...........kkkkkkkkkk...........',
];

// PAD_OVERDRIVE: red target ring — overdrive (+speed).
// Opaque colors: ackopqrw.
export const PAD_OVERDRIVE: PixelMap = [
    '...........kkkkkkkkkk...........',
    '.........kkpkorrrrrpqkk.........',
    '.....ro.koooaaooooaaooakqc......',
    '...o.akoroaorowwwwrrraoaaa......',
    '..rwrkooaacwwowwwwowwcopook.....',
    '..rrororcocwworrrrowwcocoook....',
    '...korrwwrrcoaqppqporrrwwroopo..',
    '...prcwwwrkqorrrrrroakcwwwcrp...',
    '..koacwwraorrrrrrrrrroacwwcaok..',
    '.kaooorcorrrrrroorrrrroocroorak.',
    '.koaccrarrrrrroaoorrrrroaoccrok.',
    'kaooccrarcrroorccrorrrrrarwccrak',
    'kaarccoorrroroaaoaororrroaccrppk',
    'koarooarrrrooarooraoorrrraoooaok',
    'krowwrorrrocarraarrocorrraowwork',
    'krowwrorroacaoaoraoacoorraowwork',
    'krowwrorroocoaaropoacoooraowwork',
    'krowwrorrrocarraarrocarrraowwork',
    'koarooarrrrooarooroorrrrraoooaok',
    'kaarccoorrrorooaooocorcroaccrqqk',
    'karwwcrarrrroorccroorrcrarccroak',
    '.qrwwcraorrrrroooorrrcwoqoccook.',
    '.kacrorraocrrrroorrrrrrqrroooak.',
    '..koawwwraorrrrrrrrrroarwwcark..',
    '..qkorwwwrkaorrrrrroqkrwwwroak..',
    '...koorwworroqppppporrowwrcrk...',
    '....kroorocccoorrrocccocoooao...',
    '.....kookacccowwwwocccokorkoo...',
    '......kaaoaorowwwwrroaoook......',
    '........koropaooooaqoookk.......',
    '.........kpqpooooookqkk.........',
    '...........kkkkkkkkkk...........',
];
