// Map-turret structures from the LOCKED turret-sprites sheet (native 32x32,
// box-sampled, game-palette quantized, <=10 colors each). Rendered 1:1
// (32px display); ownership, barrels, and capture arcs stay vector overlays in
// BattleScene (team identity must recolor live, sprites cannot).

type PixelMap = string[];

// TURRET_A: blue plasma ring — riveted gun-metal petals, cyan core.
// Opaque colors: bdgklpqsw.
export const TURRET_A: PixelMap = [
    '...............kk...............',
    '..............kwlk..............',
    '..............kwwk..............',
    '.........sbb..kwwk..bbs.........',
    '.......bbbbbdbdwlsbdbbbbb.......',
    '......bbbbwwbbqbbdbbwwbbbb......',
    '....dbbbwbbwbdbgbbqbwblwbbbd....',
    '....bbbwwlbwblwwwwbbwbwwwbbb....',
    '...dbbwwwwwbsbbbbbbsbwwwwwbbp...',
    '...bbbbwwgbbbbwwwwbbbbgwwbbbb...',
    '...bbwbbgbsbwlwwwwlwbsbgbbwbb...',
    '...blwwwbbllwbdbbdbwlbbbwwwlb...',
    '....sbbbbbwwbbwwwwbswwbbbbbd....',
    '....bbkbdllbbwwwwwwbblbsbkbb....',
    '.kkkddbwbwwdwwwwwwwwdwwbwbddkkk.',
    'swwlllgwbwbbwwwwwwwwbbwbwblllwws',
    'bwwlwlgwbwbbwwwwwwwwbbwbwblwlwwb',
    '.kkkddbwbwwdwwwwwwwwdwwbwbddkkk.',
    '....bbdbsllbbwwwwwwbbllbbdbb....',
    '....sbbbbbwwsbwwwwbbwwbbbbbd....',
    '...blwwwbbblwbdbbdbwlbbbwwwlb...',
    '...bbwbbgbdbwlwllwlwbsbgbbwbb...',
    '...bbbbwwgbbbbwlllbbbbgwwbbbb...',
    '...dbbwwwwwbsblgglbsbwwwwwbbd...',
    '....bbbwwwbwblwwwwbbwbwwwbbb....',
    '....bbbbwbbwbblggwbbwbbwbbbs....',
    '.....sbbbbwwbbsllbbbwwbbbbb.....',
    '......dbbbbbsbdbbdbsbbbbb.......',
    '........kbbb..kwwk..bbsk........',
    '..............kwwk..............',
    '..............kwlk..............',
    '...............kk...............',
];

// TURRET_B: red missile platform — quad launch pods, dark cab.
// Opaque colors: achklmoqrw.
export const TURRET_B: PixelMap = [
    '................................',
    '................................',
    '..kk.......a..kkkk..a.......kk..',
    '..rraka....crarrrrarca...akqrr..',
    '..rcroro..awraccccacca..rrorcr..',
    '..qrrrakqokroacwwcaookaqqorrrq..',
    '...rrrhkoramhawwwwammarakhrrrk..',
    '...rahlmcwrarowwwworarwcllhoc...',
    '....okhcwwrrcohllhocrrwwchko....',
    '....arcwwchqkkhllhkkqhcwwcra....',
    '..q..orwrmwmkkhmmhkkmwmcwro..q..',
    '.rwo.aorqmwlhkkkkkkhlwmqroa.owo.',
    '.qlqarocqqhllmh..qmllhkacoraqlq.',
    '.qhqaarrkkkhwmmmmmmlhkkqroaahmq.',
    'arcwwcwhhhkkhmmmmmmhkkhhhwwwwcra',
    'arwwwcwlllh.hmommamh.hllmwwwwcra',
    'arcwwcwmmlh.hmmmmmmh.hlmmwcwwcra',
    'arrcwcchhhkkqhmmmmhakkhhhwcwcrra',
    '.khqqqorkkkhlohmmhrlhkkkroaqqhk.',
    '.alqarocqhmlmqk..kqmlhqacoraqlq.',
    '.rwo.oarqmwlhkkkkkkhlwmqroa.owo.',
    '..a..orwrllhkkhmmhkkhlmrwro..a..',
    '....orcwwcqqkkhmmhkqqhcwwrra....',
    '....okmcwwrrwohllarworwwchko....',
    '...rahmmrcrarowwwworarwrmmhoc...',
    '...rrrhkoramhawwwwammarakhrrrk..',
    '..qrrraoqakooacwwcaookaqoarrrq..',
    '..rcrorr..acrarrrrarra..rrorcr..',
    '..rrqk....acraroorqrc....akqrr..',
    '...........a..qqqq..a...........',
    '................................',
    '................................',
];

// TURRET_C: gold siege cannon — armored mantlet, ember coils.
// Opaque colors: acdhkopqwy.
export const TURRET_C: PixelMap = [
    '................................',
    '...............dq...............',
    '..............acya..............',
    '..............ywwy..............',
    '.............koccy..............',
    '.............kywwy..............',
    '.............kywwy..............',
    '.............kywwy..............',
    '.............kywwy..............',
    '.............kywwy..............',
    '.............kywwy..............',
    '.............koccyk.............',
    '........cwooyooccoyoyowc........',
    '.......ycyoyoocwwcooyoycy.......',
    '......ycyyacoocwwcoycayycy......',
    '......oyyyacoccwwccoyayyyo......',
    '......qayaococcwwccocoayaq......',
    '.......yckccoccwwccacckcy.......',
    '......pcwawcooccccyocwacck......',
    '......ayyawcoyywwyyocwayya......',
    '......owcooyqyccyyyayyocwo......',
    '...akooycyccoccccccoccycyoyka...',
    '...yycyoyycwowccccwowcycoycyyk..',
    '..kocccooyoyocyccycoyoyyocccok..',
    '..accccyayoaoyoooocoaoyoycccca..',
    '.awyycccyaccaoaoooyaycaycccyywq.',
    'ayycycccwoooyoaooaoyooowcccycyya',
    'qqooycccoakkaccccccakkaocccyoopa',
    '.kdyyyoawo...oooooo...owaoyyyh..',
    '..ooqk..p.....pppp.....p..kqoo..',
    '................................',
    '................................',
];
