// Destroyed-wreck pixel maps, 16x16 each, facing EAST like CHASSIS in
// src/game/art.ts. Palette chars: .=transparent,k,d,m,l,w,r,g,y.
// Rendered dark-tinted and static; these read as wreckage, not robots:
// cracked hulls, transparent holes, slumped/bent silhouettes, scorch (k),
// and small amber ember dots (y).

export const WRECKS: Record<string, string[]> = {
    rusher: [
        '................',
        '...kkkkkkkk.....',
        '..kmmmmmmkk.....',
        '..kmkdkdkdmm....',
        '..kdkkkkkkddk...',
        '..kdkwwwwk..dky.',
        '..kdkwmmmk..k...',
        '..kdkwmllk..k.y.',
        '.kdkkwmllk..kk..',
        '.kdkkwmmmmk.kk..',
        '.kdkkwwwwkkkk...',
        '.kdkkkkkkkkdk...',
        '..mkdkdkdkmk....',
        '..kmmmmmmkk.....',
        '...kkkkkk.......',
        '................',
    ],
    turret: [
        '................',
        '.kkkkkkkkkkkk...',
        'kddddddddddd....',
        'kdkkkkkkkkkd....',
        'kdkwwwwwwk......',
        'kdkwmmmmmk......',
        '..kwmllllmk.....',
        '..kwmlkykmk.....',
        '..kwmlkkkmk.....',
        '..kwmllllmk...k.',
        'kdkwmmmmmk......',
        'kdkwwwwwwkkk....',
        'kdkkkkkkkkkd....',
        'kddddddddddd....',
        '.kkkkkkkkkkk....',
        '..........k.....',
    ],
    orbiter: [
        '................',
        '................',
        '....kkkkkk......',
        '..kkmmmmmmm.....',
        '.kmmkkkkkkk.....',
        '.kmkwwwwkwk.....',
        '.kmkwmmym.......',
        'kmmkwmllw.......',
        '.kmkwmllmkk.....',
        '..mkwmmmmkky....',
        '..mkwwwwwwkk....',
        '..mmkkkkkkkmm...',
        '...kkmmmmmmk....',
        '....kkkkkk......',
        '....kkk....k....',
        '................',
    ],
    wanderer: [
        '................',
        '................',
        '...kkmmmmkk.....',
        '..kmmmlllmm.....',
        '..mmllwwwllm....',
        '.kmmlwwwwww.....',
        'kmmldwmmmmd.....',
        'kmmldwmkkmw.....',
        '.mmldwmkkmkk....',
        '.mmldwmmmmyk....',
        '.kmmlwwwwwwk....',
        '.kmmllwwwwllm...',
        '..kmmmllllmmmk..',
        '...kkmmmmmmkkk..',
        '.....kkkkkk.....',
        '................',
    ],
    hunter: [
        '................',
        '..kkkkwkk.......',
        '.kmmmmmmmkk.....',
        '.kmkdkdkdmkk....',
        '.kdkkkkkkkdd....',
        '.kdkwwwwkwk.....',
        '.kdkwmmmmkk.....',
        '.kdkwmkklyk.....',
        '.kdkwmkkkmk...k.',
        '.kdkwmmmmmk.....',
        '.kdkwwwwkwk.....',
        '.kdkkkkkkkddk...',
        '.kmkdkdkdmk.....',
        '.kmmmmmmmkkk....',
        '..kkkkkkkk......',
        '....y.....k.....',
    ],
};
